# Generated by Django 4.0.1 on 2022-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_lesson_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(max_length=128),
        ),
    ]
